### ISSUE TITLE
yo@1.0.0 not available anymore

### ISSUE THREAD

**Issue by CoRfr** [ceph/calamari-clients#87]
Hi,

It seems the build depends on yo 1.0.0, which is apparently not provided anymore.

npm ERR! notarget No compatible version found: yo@'>=1.0.0-0 <1.1.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.1.0","1.1.1","1.1.2","1.2.0","1.2.1","1.3.0","1.3.2","1.3.3"]

I replaced the version by 1.1.0 in admin & login package.json and it build fine.

Bertrand

**Comment by CoRfr** [comment]
My bad, it's already fixed in https://github.com/ceph/calamari-clients/commit/0cbcfbaa791baa3ee25c4f1a135f005c1d568512

**Comment by dmick** [comment]
Yep.  Thanks for the report anyway.
